### ISSUE TITLE
Textarea label misplaced

### ISSUE THREAD

**Issue by Rewerson** [beercss/beercss#372] opened 2024-09-10 08:21 UTC
See simple example below.
![image](https://github.com/user-attachments/assets/446c2393-c299-405d-9a64-cd72d6d622ee)
After focusing on textarea, label transits on top as needed, but basically it doesn't respect field content.

**Comment by guidouil** [comment] 2024-09-10 10:10
I made a [simple codepen](https://codepen.io/guidouil/pen/KKjJObv) to reproduce and I don't see the issue.
Are you using 3.7.7 version ?

**Comment by Rewerson** [comment] 2024-09-10 10:13
Yes, 3.7.7.
Pre-fill textarea with some text, and you'll see.

**Comment by guidouil** [comment] 2024-09-10 12:21
I remember this one, the label has to get an active class if textarea is already filled when showing page.
[Read The Friendly Manuel](https://github.com/beercss/beercss/blob/main/docs/TEXTAREA.md#method-1) 😁
Cheers🍻

**Comment by Rewerson** [comment] 2024-09-10 12:29
Thanks, but it worked fine in 3.6.x, so i reported this as a bug.
Also, as documented: the JS file of beer do this automatically.
It's my case, I use mentioned JS.
On your codepen example just switch to 3.6.13, and you no longer need to set class="active" to textarea by hands.

**Comment by leonardorafael** [comment] 2024-09-10 15:15
Fixed in https://github.com/beercss/beercss/releases/tag/v3.7.8
This issue was caused by our JS refactoring.

**Closed by leonardorafael** 2024-09-10 15:15 UTC
Labels: bug
