### ISSUE TITLE
Firefox - Inputfields in details with value won't initialize right

### ISSUE THREAD

**Issue by AlTrAugsburg** [beercss/beercss#58] opened 2022-05-05 08:21 UTC
If you put an input field into an detail with a value before ui() is called, the borderline will be calculated wrong.

Codepen Example: https://codepen.io/AlTrAugsburg/pen/PoQqLry

Steps to replicate:
1. Put an input with label into a detail (not the summary).
2.  Give it a value to start, which is not empty. 
3. Then call the function ui().
4. Open the detail and the border of the input was not calculated right and the borderline will go through the label text.

My fix:
Open all details, call ui() and then close them again. But it's not the most pretty fix.

Maybe this fix or a better one could be included into the ui() function.

Thanks in advance.

**Comment by leonardorafael** [comment] 2022-05-09 20:12
Hi @AlTrAugsburg, thanks for the catch. But I can't reproduce this issue. Someone else here?

**Comment by laurentpayot** [comment] 2022-05-10 06:14
Is that the issue ?
![image](https://user-images.githubusercontent.com/2776142/167560179-c2ae9e36-126f-4935-a0b4-2d9b7bf1c690.png)

I could get it both in Chrome and Firefox, but I cannot really tell how. I had to focus the input and refresh the codepen page. But sometimes it would work...

**Comment by AlTrAugsburg** [comment] 2022-05-10 07:35
Jep, that's the one.

When I created this issue, I only tested it in Firefox on Android (Version 100.1.1) and Linux (Version 99.0), because it's the browser I daily drive. I tested it now in Chrome on Android  (Version 101) and Chromium on Linux (also Version 101) and there it seems to be rendered right. Maybe it's a Firefox only issue.

**Comment by laurentpayot** [comment] 2022-05-10 08:58
I edited my comment. I couldn’t reproduce it in Chrome. So yes maybe it’s a Firefox issue.

By the way as I’m not using Beercss JavaScript functions (in this case I’m using `padding-inline: 5rem` and directly set `background-color` in my framework) so I cannot tell for my app...

**Comment by leonardorafael** [comment] 2022-05-10 14:36
@laurentpayot and @AlTrAugsburg, thanks for help. I will investigate how we can fix it on Firefox. We decided to clip the input field instead to change the background-color of label, because the background of container can be an image, a gradient color or any mix of color, rather than a solid color. We will try to fix this on Firefox soon.

**Comment by AlTrAugsburg** [comment] 2022-05-10 18:46
@laurentpayot thanks for your help, but I'll stick to ui(). I don't have that much experience in web development, so I'm happy, when my application does, what is it meant to do 😅 But I appreciate it.
@leonardorafael that sounds good. Thank you for your help and time 👍🏼 Happy to help, when there's something I can contribute

**Comment by laurentpayot** [comment] 2022-05-11 08:11
@AlTrAugsburg I do things in a special way because of my framework ([Elm](https://elm-lang.org/)).  `ui()` is just great :slightly_smiling_face:  

@leonardorafael 
> We decided to clip the input field instead to change the background-color of label, because the background of container can be an image, a gradient color or any mix of color, rather than a solid color.

I was wondering. That totaly makes sense now :+1:

**Comment by AlTrAugsburg** [comment] 2022-07-02 18:28
Because of the new implementation of the ui()-function in version 2.1.0, I tested the example again, and it seems, that the issue doesn't occur anymore, probably it renders it automatically, when it gets visible (my best guess).

Made a simple codepen to show it with the version 2.1.0: https://codepen.io/AlTrAugsburg/pen/YzaXEJM

Would be great, if someone could double check, because then this issue could be closed.

**Comment by leonardorafael** [comment] 2022-07-04 13:28
I double checked here, seems ok. I will close this issue right now. Thanks @AlTrAugsburg

**Closed by leonardorafael** 2022-07-04 13:28 UTC
Labels: bug
